[book]
authors = ["saylesss88"]
language = "en"
src = "src"
title = "privacy-book"

[preprocessor.rss-feed]
renderers = ["html"]

[preprocessor.frontmatter-strip]
renderers = ["html"]

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[output.html]
additional-css = ["theme/header-buttons.css"]
additional-js = ["theme/header-buttons.js"]
